export const ERROR_ADDING_NETWORK = 'ERROR_ADDING_NETWORK';
export const CONNECT_FAILED_TIMEOUT = 'CONNECT_FAILED_TIMEOUT';
export const SSID_WIFI_DEVICE = 'WIFI_ESP32';
export const KEY_JOBLIST_STORAGE = 'JOB_LIST';
export const KEY_USER_LOGGED = 'USER_LOGGED';
export const KEY_DEVICES_MODIFIES = 'DEVICE_MODIFIES';
export const KEY_IS_FIRST = 'IS_FIRST';
